import {
  MissionGiver,
  MissionType,
  MissionReward,
  PartTier,
} from "@/types/game";

export interface MissionTemplate {
  id: string;
  giver: MissionGiver;
  type: MissionType;
  label: string;
  description: string;
  target: number;
  reward: MissionReward;
  weight?: number;
  minRepTier?: number;
  maxRepTier?: number;
  minTierCrafted?: PartTier;
  requiresBaronSeen?: boolean;
  requiresRdUnlocked?: boolean;
  requiresFreedomBuild?: boolean;
  requiresFreedomController?: boolean;
  requiresCompatibleUnlocked?: boolean;
  chainId?: string;
  chainIndex?: number;
  chainLength?: number;
}

export const MISSION_TEMPLATES: MissionTemplate[] = [
  {
    id: "mentor_merge_flow",
    giver: "mentor",
    type: "merge_count",
    label: "Merge 6 times",
    description: "Momentum unlocks better parts. Keep the chain going.",
    target: 6,
    reward: { cash: 30, reputation: 5 },
    weight: 1.0,
  },
  {
    id: "customer_install_sprint",
    giver: "customer",
    type: "complete_order",
    label: "Complete 3 installs",
    description: "Satisfied clients spread the word. Keep installs flowing.",
    target: 3,
    reward: { cash: 45, reputation: 10 },
    weight: 0.9,
  },
  {
    id: "mentor_open_installs",
    giver: "mentor",
    type: "complete_order_no_locked",
    label: "Complete 2 open-only installs",
    description:
      "Open installs keep your options flexible and research steady.",
    target: 2,
    reward: { reputation: 10, research: 6 },
    weight: 1.0,
    minRepTier: 1,
  },
  {
    id: "baron_locked_installs",
    giver: "baron",
    type: "complete_order_with_locked",
    label: "Complete 2 locked installs",
    description: "Certified installs pay fast. Keep the locks coming.",
    target: 2,
    reward: { cash: 90, reputation: 6 },
    weight: 0.8,
    minRepTier: 2,
    requiresBaronSeen: true,
  },
  {
    id: "mentor_reach_tier4",
    giver: "mentor",
    type: "reach_tier",
    label: "Reach Tier 4",
    description: "Smart Kits unlock higher-paying installs.",
    target: 4,
    reward: { reputation: 15, research: 10 },
    weight: 0.9,
    minRepTier: 2,
    minTierCrafted: 2,
  },
  {
    id: "baron_accept_offer",
    giver: "baron",
    type: "accept_baron_offer",
    label: "Accept a Baron offer",
    description: "Deals accelerate growth—at a price.",
    target: 1,
    reward: { cash: 80, reputation: 4 },
    weight: 0.6,
    minRepTier: 2,
    requiresBaronSeen: true,
  },
  {
    id: "rd_craft_controller",
    giver: "rd",
    type: "craft_freedom_controller",
    label: "Craft a Freedom Controller",
    description: "Build the tool that breaks dependency locks.",
    target: 1,
    reward: { research: 20, reputation: 8 },
    weight: 0.8,
    minRepTier: 2,
    requiresFreedomBuild: true,
  },
  {
    id: "rd_use_controller",
    giver: "rd",
    type: "use_freedom_controller",
    label: "Use a Freedom Controller",
    description: "Convert a locked part into open-compatible tech.",
    target: 1,
    reward: { research: 12, reputation: 6 },
    weight: 0.7,
    minRepTier: 2,
    requiresFreedomController: true,
  },
  {
    id: "rd_compat_install",
    giver: "rd",
    type: "complete_order_compatible",
    label: "Complete 1 compatible install",
    description: "Liberated tech earns premium respect.",
    target: 1,
    reward: { research: 18, reputation: 10 },
    weight: 0.7,
    minRepTier: 3,
    requiresCompatibleUnlocked: true,
  },
  {
    id: "milestone_tier5",
    giver: "system",
    type: "fulfill_tier5_order",
    label: "Fulfill a Tier 5 install",
    description: "Signature systems prove you’ve arrived.",
    target: 1,
    reward: { cash: 150, reputation: 30 },
    weight: 0.6,
    minRepTier: 3,
    minTierCrafted: 5,
  },
  {
    id: "milestone_tier10",
    giver: "system",
    type: "fulfill_tier10_order",
    label: "Fulfill a Tier 10 install",
    description: "Kingdom installs define your legacy.",
    target: 1,
    reward: { cash: 400, reputation: 60, research: 20 },
    weight: 0.4,
    minRepTier: 4,
    minTierCrafted: 10,
  },

  // Mentor episode: Open Standards
  {
    id: "open_path_1",
    giver: "mentor",
    type: "complete_order_no_locked",
    label: "Open Path I: 2 open installs",
    description: "Open installs build the long game.",
    target: 2,
    reward: { reputation: 12, research: 8 },
    weight: 0.7,
    minRepTier: 1,
    chainId: "open_path",
    chainIndex: 1,
    chainLength: 3,
  },
  {
    id: "open_path_2",
    giver: "mentor",
    type: "reach_tier",
    label: "Open Path II: Reach Tier 4",
    description: "Smart Kits keep you ahead without lock-in.",
    target: 4,
    reward: { reputation: 18, research: 12 },
    minRepTier: 2,
    minTierCrafted: 2,
    chainId: "open_path",
    chainIndex: 2,
    chainLength: 3,
  },
  {
    id: "open_path_3",
    giver: "mentor",
    type: "craft_freedom_controller",
    label: "Open Path III: Craft the Controller",
    description: "Freedom tech ends dependency loops.",
    target: 1,
    reward: { reputation: 20, research: 20 },
    minRepTier: 2,
    requiresFreedomBuild: true,
    chainId: "open_path",
    chainIndex: 3,
    chainLength: 3,
  },

  // Baron episode: Certified Rise
  {
    id: "certified_path_1",
    giver: "baron",
    type: "accept_baron_offer",
    label: "Certified Rise I: Take a deal",
    description: "Crownlight offers the fast lane.",
    target: 1,
    reward: { cash: 110, reputation: 10 },
    minRepTier: 2,
    requiresBaronSeen: true,
    weight: 0.6,
    chainId: "certified_path",
    chainIndex: 1,
    chainLength: 3,
  },
  {
    id: "certified_path_2",
    giver: "baron",
    type: "complete_order_with_locked",
    label: "Certified Rise II: 2 locked installs",
    description: "Certified kits move faster with Crownlight’s blessing.",
    target: 2,
    reward: { cash: 130, reputation: 12 },
    minRepTier: 2,
    requiresBaronSeen: true,
    chainId: "certified_path",
    chainIndex: 2,
    chainLength: 3,
  },
  {
    id: "certified_path_3",
    giver: "baron",
    type: "fulfill_tier5_order",
    label: "Certified Rise III: Tier 5 install",
    description: "Only signature systems qualify.",
    target: 1,
    reward: { cash: 220, reputation: 30 },
    minRepTier: 3,
    minTierCrafted: 5,
    requiresBaronSeen: true,
    chainId: "certified_path",
    chainIndex: 3,
    chainLength: 3,
  },

  // R&D episode: Compatibility Loop
  {
    id: "compat_path_1",
    giver: "rd",
    type: "craft_freedom_controller",
    label: "Compatibility Loop I: Craft the Controller",
    description: "We need the tool before we can liberate parts.",
    target: 1,
    reward: { research: 20, reputation: 10 },
    minRepTier: 2,
    requiresFreedomBuild: true,
    chainId: "compat_path",
    chainIndex: 1,
    chainLength: 3,
  },
  {
    id: "compat_path_2",
    giver: "rd",
    type: "use_freedom_controller",
    label: "Compatibility Loop II: Use a Controller",
    description: "Convert a locked kit into a compatible one.",
    target: 1,
    reward: { research: 15, reputation: 8 },
    minRepTier: 2,
    requiresFreedomController: true,
    chainId: "compat_path",
    chainIndex: 2,
    chainLength: 3,
  },
  {
    id: "compat_path_3",
    giver: "rd",
    type: "complete_order_compatible",
    label: "Compatibility Loop III: Compat install",
    description: "Prove the liberated tech works in the field.",
    target: 1,
    reward: { research: 25, reputation: 15 },
    minRepTier: 3,
    requiresCompatibleUnlocked: true,
    chainId: "compat_path",
    chainIndex: 3,
    chainLength: 3,
  },
];
