import {
  ProjectDefinition,
  SiteRuleDefinition,
  SiteRuleId,
} from "@/types/game";

const NARRATIVE_GENERIC = {
  offer: "project_offer_generic",
  accept: "project_accept_generic",
  stageComplete: "project_stage_complete_generic",
  fail: "project_fail_generic",
  complete: "project_complete_generic",
};

export const SITE_RULES: Record<SiteRuleId, SiteRuleDefinition> = {
  public_scrutiny: {
    id: "public_scrutiny",
    name: "Public Scrutiny",
    tagline: "Every install is visible.",
    upsideText: "Open-only installs gain +15% reputation.",
    downsideText: "Order refresh costs +30% more.",
    effects: {
      openOnlyRepMult: 1.15,
      orderRefreshCostMult: 1.3,
    },
  },
  storm_protocol: {
    id: "storm_protocol",
    name: "Storm Protocol",
    tagline: "Weather windows close fast.",
    upsideText: "Compatibility installs gain +15% cash.",
    downsideText: "New rush order timers are 20% shorter.",
    effects: {
      compatCashMult: 1.15,
      rushDeadlineMult: 0.8,
    },
  },
  union_scheduling: {
    id: "union_scheduling",
    name: "Union Scheduling",
    tagline: "Stronger milestones, slower sourcing.",
    upsideText: "Project stage rewards gain +12%.",
    downsideText: "Open supplier cooldown is 25% longer.",
    effects: {
      projectStageRewardMult: 1.12,
      openSupplierCooldownMult: 1.25,
    },
  },
  safety_lock: {
    id: "safety_lock",
    name: "Safety Lock",
    tagline: "Compliance first, no shortcuts.",
    upsideText: "Eco-audit research bonus gains +35%.",
    downsideText: "Order refresh is disabled.",
    effects: {
      ecoAuditBonusResearchMult: 1.35,
      disallowOrderRefresh: true,
    },
  },
};

export function getSiteRuleForProjectStage(
  project: ProjectDefinition,
  stageIndex: number,
) {
  const stageRuleId = project.stages[stageIndex]?.siteRuleId;
  const ruleId = stageRuleId ?? project.siteRuleId;
  if (!ruleId) return null;
  return SITE_RULES[ruleId] ?? null;
}

export const PROJECT_DEFINITIONS: ProjectDefinition[] = [
  {
    id: "proj_neon_city_grid",
    title: "Neon City Grid Reboot",
    locationName: "Neon City - Municipal Core",
    siteRuleId: "public_scrutiny",
    client: { name: "Mayor Marisol Vance", role: "Mayor", tone: "demanding" },
    synopsis:
      "Replace legacy street lighting with open-standard infrastructure. Public visibility is massive.",
    introHeadline: "Public grid, public stakes.",
    introNarrative:
      "Mayor Marisol Vance wants the city grid rebuilt in the open, with every block watching. The Mentor warns that visibility cuts both ways. Tina answers: if the lights are honest, so are the standards.",
    projectCardIcon: "project_card_neon_city_grid",
    clientPortrait: "portrait_mayor_vance",
    trophyIcon: "trophy_city_grid",
    trophyName: "City Grid Key",
    locationBackdrop: "backdrop_neon_city_municipal",
    unlock: { phaseMin: 2, minRepTier: 4 },
    deposit: { formulaKey: "early" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Survey & Pilot Block",
        orderSpec: { targetTierRange: [4, 5], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.2, researchBonusFlat: 6 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop Intersection",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.1 },
      },
      {
        stageIndex: 2,
        stageTitle: "Eco Compliance Audit",
        orderSpec: {
          targetTierRange: [6, 7],
          requiresOpenOnly: true,
          ecoAudit: true,
        },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.6, repBonusFlat: 18 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 3,
        stageTitle: "Grid Switch-over Ceremony",
        orderSpec: {
          targetTierRange: [8, 8],
          requiresCompatibility: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.4 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
    ],
    completionRewards: {
      cashMultiplier: 1.6,
      reputationMultiplier: 1.4,
      researchMultiplier: 1.4,
    },
    permanentPerk: "Municipal Trust",
    perkDescription: "Municipal Trust: +5% cash on open-only installs.",
    trophyId: "trophy_city_grid",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_festival_main_stage",
    title: "Festival of Sparks: Main Stage",
    locationName: "Riverfront Festival Grounds",
    siteRuleId: "storm_protocol",
    client: { name: "Aria Kale", role: "Festival Director", tone: "visionary" },
    synopsis:
      "A spectacle contract with high stakes and zero tolerance for failure.",
    introHeadline: "A stage that cannot blink.",
    introNarrative:
      "Aria Kale wants a show that never flickers, even when the crowd is the size of a city. The Mentor calls it a stress test in disguise. Tina calls it a chance to make open tech feel legendary.",
    projectCardIcon: "project_card_festival_main_stage",
    clientPortrait: "portrait_aria_kale",
    trophyIcon: "trophy_backstage_pass",
    trophyName: "Backstage Pass",
    locationBackdrop: "backdrop_riverfront_festival",
    unlock: { phaseMin: 2, minRepTier: 5 },
    deposit: { formulaKey: "early" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Prototype Sequence",
        orderSpec: { targetTierRange: [5, 5], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.3 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Power & Safety Check",
        orderSpec: {
          targetTierRange: [6, 6],
          requiresOpenOnly: true,
          ecoAudit: true,
        },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.5, repBonusFlat: 18 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 2,
        stageTitle: "Showtime Rig",
        orderSpec: {
          targetTierRange: [8, 9],
          requiresCompatibility: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.6 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
    ],
    completionRewards: {
      cashMultiplier: 1.6,
      reputationMultiplier: 1.4,
      researchMultiplier: 1.4,
    },
    permanentPerk: "Showtime Reputation",
    perkDescription: "Showtime Reputation: +5% reputation from rush installs.",
    trophyId: "trophy_backstage_pass",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_harbor_beacon",
    title: "Harbor Beacon Modernization",
    locationName: "Old Harbor Lighthouse District",
    siteRuleId: "storm_protocol",
    client: { name: "Chief Rourke", role: "Port Authority", tone: "skeptical" },
    synopsis:
      "Reliability contract where weather, corrosion, and public safety matter more than flash.",
    introHeadline: "Stormproof reliability.",
    introNarrative:
      "Chief Rourke cares about one thing: the beacon never fails in a storm. Salt, lightning, and inspection logs will punish shortcuts. Tina agrees to build for trust, not applause.",
    projectCardIcon: "project_card_harbor_beacon",
    clientPortrait: "portrait_chief_rourke",
    trophyIcon: "trophy_harbor_lantern",
    trophyName: "Harbor Lantern",
    locationBackdrop: "backdrop_old_harbor",
    unlock: { phaseMin: 2, minRepTier: 5 },
    deposit: { formulaKey: "early" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Saltproof Retrofit",
        orderSpec: { targetTierRange: [5, 6], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.2 },
        failPenalty: { type: "pressure", pressureIncrease: 5 },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop with Navigation Systems",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.1 },
      },
      {
        stageIndex: 2,
        stageTitle: "Storm Drill",
        orderSpec: {
          targetTierRange: [7, 7],
          requiresOpenOnly: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 1.8 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 3,
        stageTitle: "Beacon Commissioning",
        orderSpec: { targetTierRange: [8, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.2 },
        failPenalty: { type: "pressure", pressureIncrease: 7 },
      },
    ],
    completionRewards: {
      cashMultiplier: 1.6,
      reputationMultiplier: 1.4,
      researchMultiplier: 1.4,
    },
    permanentPerk: "Reliability Stamp",
    perkDescription: "Reliability Stamp: recycling yields slightly more.",
    trophyId: "trophy_harbor_lantern",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_metro_wayfinding",
    title: "Metro Wayfinding Overhaul",
    locationName: "Underground Metro Line",
    siteRuleId: "union_scheduling",
    client: {
      name: "Commissioner Han",
      role: "Transit Commissioner",
      tone: "demanding",
    },
    synopsis:
      "Systemwide footprint and repetitive installs that test scalable operations.",
    introHeadline: "Scale without drift.",
    introNarrative:
      "Commissioner Han wants a system that works for everyone, everywhere, every hour. This is a scale problem, not a single install. The Mentor says consistency is the real innovation; Tina says prove it across the network.",
    projectCardIcon: "project_card_metro_wayfinding",
    clientPortrait: "portrait_commissioner_han",
    trophyIcon: "trophy_metro_badge",
    trophyName: "Metro Badge",
    locationBackdrop: "backdrop_underground_metro",
    unlock: { phaseMin: 2, minRepTier: 6 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Platform Pilot",
        orderSpec: { targetTierRange: [5, 6], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.2 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Accessibility Compliance",
        orderSpec: {
          targetTierRange: [6, 6],
          ecoAudit: true,
          requiresOpenOnly: true,
        },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4, repBonusFlat: 20 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 2,
        stageTitle: "Interop Signaling",
        orderSpec: { targetTierRange: [7, 7], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.6 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
      {
        stageIndex: 3,
        stageTitle: "Night Service Rush",
        orderSpec: { targetTierRange: [7, 8], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 1.9 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 4,
        stageTitle: "Systemwide Launch",
        orderSpec: {
          targetTierRange: [9, 9],
          requiresCompatibility: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.7 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
    ],
    completionRewards: {
      cashMultiplier: 1.9,
      reputationMultiplier: 1.6,
      researchMultiplier: 1.5,
    },
    permanentPerk: "Transit Contract Pipeline",
    perkDescription:
      "Transit Contract Pipeline: premium orders appear slightly more often.",
    trophyId: "trophy_metro_badge",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_skyline_tower_facade",
    title: "Skyline Tower Signature Facade",
    locationName: "Glassspire Financial Tower",
    siteRuleId: "public_scrutiny",
    client: {
      name: "Liaison Sato",
      role: "Executive Liaison",
      tone: "demanding",
    },
    synopsis:
      "Prestige client with zero tolerance for public failure and huge visibility upside.",
    introHeadline: "Prestige, no mistakes.",
    introNarrative:
      "The Glassspire tower is a skyline signature; every flaw is a headline. Liaison Sato is buying certainty as much as light. Tina commits to a facade that earns industry myth status.",
    projectCardIcon: "project_card_skyline_tower",
    clientPortrait: "portrait_liaison_sato",
    trophyIcon: "trophy_glasspire_plaque",
    trophyName: "Glasspire Plaque",
    locationBackdrop: "backdrop_glassspire_tower",
    unlock: { phaseMin: 2, minRepTier: 6 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Design Mock-Up",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Energy Efficiency Certification",
        orderSpec: {
          targetTierRange: [6, 7],
          requiresOpenOnly: true,
          ecoAudit: true,
        },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.6, researchBonusFlat: 12 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 2,
        stageTitle: "Facade Rollout",
        orderSpec: { targetTierRange: [8, 8], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 3,
        stageTitle: "Penthouse Showcase",
        orderSpec: { targetTierRange: [9, 9], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.6 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
    ],
    completionRewards: {
      cashMultiplier: 1.9,
      reputationMultiplier: 1.6,
      researchMultiplier: 1.5,
    },
    permanentPerk: "Prestige Clientele",
    perkDescription:
      "Prestige Clientele: +5% cash from compatibility-required orders.",
    trophyId: "trophy_glasspire_plaque",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_childrens_hospital",
    title: "Children's Hospital Nightlight Wing",
    locationName: "St. Luma Children's Hospital",
    siteRuleId: "safety_lock",
    client: { name: "Dr. Imani Reyes", role: "Chief Physician", tone: "warm" },
    synopsis:
      "Safety-first install with high scrutiny and high community stakes.",
    introHeadline: "Comfort without compromise.",
    introNarrative:
      "Dr. Imani Reyes wants a wing that feels safe before it feels bright. This is about care, not speed. The Mentor says rush invites risk; Tina says they will do it right.",
    projectCardIcon: "project_card_childrens_hospital",
    clientPortrait: "portrait_dr_reyes",
    trophyIcon: "trophy_nightlight_ribbon",
    trophyName: "Nightlight Ribbon",
    locationBackdrop: "backdrop_st_luma_hospital",
    unlock: { phaseMin: 2, minRepTier: 7 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Safety First Retrofit",
        orderSpec: {
          targetTierRange: [6, 7],
          requiresOpenOnly: true,
          ecoAudit: true,
        },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.5, repBonusFlat: 24 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop Monitoring",
        orderSpec: { targetTierRange: [7, 7], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.7 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
      {
        stageIndex: 2,
        stageTitle: "Wing Opening",
        orderSpec: { targetTierRange: [9, 9], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 2.5, repBonusFlat: 40 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
    ],
    completionRewards: {
      cashMultiplier: 1.9,
      reputationMultiplier: 1.6,
      researchMultiplier: 1.5,
    },
    permanentPerk: "Community Trust",
    perkDescription:
      "Community Trust: Phase 2 pressure tax is slightly reduced.",
    trophyId: "trophy_nightlight_ribbon",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_museum_exhibit",
    title: "Museum of Light: Retrospective Exhibit",
    locationName: "Museum of Light",
    siteRuleId: "union_scheduling",
    client: { name: "Curator Elowen Shaw", role: "Curator", tone: "visionary" },
    synopsis:
      "A creative contract that leans into compatibility sets and signature builds.",
    introHeadline: "A signature exhibit.",
    introNarrative:
      "Curator Elowen Shaw wants a retrospective that feels alive. Compatibility is part of the art, and every stage is a signature build. Tina promises the exhibit will make open standards feel inevitable.",
    projectCardIcon: "project_card_museum_exhibit",
    clientPortrait: "portrait_curator_shaw",
    trophyIcon: "trophy_curator_seal",
    trophyName: "Curator's Seal",
    locationBackdrop: "backdrop_museum_of_light",
    unlock: { phaseMin: 2, minRepTier: 7 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Gallery Concept Install",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Restoration Room Efficiency",
        orderSpec: {
          targetTierRange: [6, 7],
          requiresOpenOnly: true,
          ecoAudit: true,
        },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.6 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 2,
        stageTitle: "Interactive Corridor",
        orderSpec: { targetTierRange: [7, 7], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.7 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
      {
        stageIndex: 3,
        stageTitle: "Press Night Rush",
        orderSpec: { targetTierRange: [8, 8], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 4,
        stageTitle: "Featured Piece: Freedom in Light",
        orderSpec: { targetTierRange: [9, 10], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.8 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
    ],
    completionRewards: {
      cashMultiplier: 1.9,
      reputationMultiplier: 1.6,
      researchMultiplier: 1.5,
    },
    permanentPerk: "Exhibit Prestige",
    perkDescription:
      "Exhibit Prestige: small research bonus on compatibility installs.",
    trophyId: "trophy_curator_seal",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_stadium_halftime",
    title: "Stadium Halftime Spectacle",
    locationName: "Titan Field Stadium",
    siteRuleId: "storm_protocol",
    client: { name: "Jax Moreno", role: "Head of Events", tone: "demanding" },
    synopsis:
      "A pressure contract packed with rush installs and a high payout ceiling.",
    introHeadline: "The city watches live.",
    introNarrative:
      "Jax Moreno demands a halftime that hits like thunder. Everything is timed, everything is public. The Mentor calls it a discipline test; Tina calls it a proving ground.",
    projectCardIcon: "project_card_stadium_halftime",
    clientPortrait: "portrait_jax_moreno",
    trophyIcon: "trophy_halftime",
    trophyName: "Halftime Trophy",
    locationBackdrop: "backdrop_titan_field",
    unlock: { phaseMin: 2, minRepTier: 8 },
    deposit: { formulaKey: "late" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Rig Test",
        orderSpec: { targetTierRange: [7, 7], rush: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 1.7 },
        failPenalty: { type: "pressure", pressureIncrease: 7 },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop Broadcast Sync",
        orderSpec: { targetTierRange: [8, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
      {
        stageIndex: 2,
        stageTitle: "Halftime Main System",
        orderSpec: {
          targetTierRange: [10, 10],
          requiresCompatibility: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 5 },
        stageRewards: { rewardMultiplier: 3.0 },
        failPenalty: { type: "pressure", pressureIncrease: 10 },
      },
    ],
    completionRewards: {
      cashMultiplier: 2.3,
      reputationMultiplier: 1.8,
      researchMultiplier: 1.6,
    },
    permanentPerk: "Stadium Grade",
    perkDescription: "Stadium Grade: +5% cash on rush orders.",
    trophyId: "trophy_halftime",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_airport_runway",
    title: "Airport Runway Guidance Upgrade",
    locationName: "Neon City International Airport",
    siteRuleId: "safety_lock",
    client: {
      name: "Inspector Wren",
      role: "Safety Inspector",
      tone: "skeptical",
    },
    synopsis: "High scrutiny and procedural checks with a legitimacy payoff.",
    introHeadline: "Safety written in light.",
    introNarrative:
      "Inspector Wren will audit every fixture and every claim. The runway demands precision under pressure. Tina agrees to treat the upgrade like policy, not preference.",
    projectCardIcon: "project_card_airport_runway",
    clientPortrait: "portrait_inspector_wren",
    trophyIcon: "trophy_clearance_badge",
    trophyName: "Clearance Badge",
    locationBackdrop: "backdrop_neon_airport",
    unlock: { phaseMin: 2, minRepTier: 8 },
    deposit: { formulaKey: "late" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Taxiway Prototype",
        orderSpec: { targetTierRange: [7, 7], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.6 },
        failPenalty: { type: "pressure", pressureIncrease: 7 },
      },
      {
        stageIndex: 1,
        stageTitle: "Compliance Audit",
        orderSpec: { targetTierRange: [7, 8], ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.8 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 2,
        stageTitle: "Interop Control Integration",
        orderSpec: { targetTierRange: [8, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.1 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
      {
        stageIndex: 3,
        stageTitle: "Runway Commission",
        orderSpec: {
          targetTierRange: [10, 10],
          ecoAudit: true,
          requiresOpenOnly: true,
        },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 3.0 },
        failPenalty: { type: "pressure", pressureIncrease: 10 },
      },
    ],
    completionRewards: {
      cashMultiplier: 2.3,
      reputationMultiplier: 1.8,
      researchMultiplier: 1.6,
    },
    permanentPerk: "Certified Contractor",
    perkDescription:
      "Certified Contractor: project deposits cost slightly less.",
    trophyId: "trophy_clearance_badge",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_international_expo",
    title: "International Light Expo Pavilion",
    locationName: "World Light Expo Grounds",
    siteRuleId: "public_scrutiny",
    client: { name: "Chair Solenne", role: "Expo Chair", tone: "visionary" },
    synopsis:
      "The capstone contract that crowns you as the industry standard-setter.",
    introHeadline: "The world stage.",
    introNarrative:
      "Chair Solenne wants the pavilion remembered long after the fireworks fade. This is the capstone that proves open standards can lead the industry. The Mentor calls it the spotlight; Tina plans to own it.",
    projectCardIcon: "project_card_international_expo",
    clientPortrait: "portrait_expo_chair_solenne",
    trophyIcon: "trophy_expo_laurel",
    trophyName: "Expo Laurel",
    locationBackdrop: "backdrop_world_expo",
    unlock: { phaseMin: 2, minRepTier: 9, minProjectsCompleted: 6 },
    deposit: { formulaKey: "capstone" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Prototype Showcase",
        orderSpec: { targetTierRange: [7, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.8 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 1,
        stageTitle: "Open Standard Demonstration",
        orderSpec: { targetTierRange: [8, 8], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: {
          type: "rep_debuff",
          repMultiplier: 0.9,
          remainingOrders: 3,
        },
      },
      {
        stageIndex: 2,
        stageTitle: "Sustainability Certification",
        orderSpec: {
          targetTierRange: [8, 9],
          requiresOpenOnly: true,
          ecoAudit: true,
        },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 2.2 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
      {
        stageIndex: 3,
        stageTitle: "Press Deadline Rush",
        orderSpec: { targetTierRange: [9, 9], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.6 },
        failPenalty: { type: "pressure", pressureIncrease: 10 },
      },
      {
        stageIndex: 4,
        stageTitle: "Main Pavilion System",
        orderSpec: {
          targetTierRange: [10, 10],
          requiresCompatibility: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 5 },
        stageRewards: { rewardMultiplier: 3.5 },
        failPenalty: { type: "pressure", pressureIncrease: 12 },
      },
    ],
    completionRewards: {
      cashMultiplier: 3.0,
      reputationMultiplier: 2.2,
      researchMultiplier: 1.8,
    },
    permanentPerk: "Industry Standard-Setter",
    perkDescription:
      "Industry Standard-Setter: compatibility rewards improve and Phase 2 pressure tax eases slightly.",
    trophyId: "trophy_expo_laurel",
    narrativeBeats: NARRATIVE_GENERIC,
  },
];

export const PROJECT_DEFINITION_BY_ID = new Map(
  PROJECT_DEFINITIONS.map((project) => [project.id, project]),
);
