import { ProjectDefinition } from "@/types/game";

const NARRATIVE_GENERIC = {
  offer: "project_offer_generic",
  accept: "project_accept_generic",
  stageComplete: "project_stage_complete_generic",
  fail: "project_fail_generic",
  complete: "project_complete_generic",
};

export const PROJECT_DEFINITIONS: ProjectDefinition[] = [
  {
    id: "proj_neon_city_grid",
    title: "Neon City Grid Reboot",
    locationName: "Neon City - Municipal Core",
    client: { name: "Mayor Marisol Vance", role: "Mayor", tone: "demanding" },
    synopsis:
      "Replace legacy street lighting with open-standard infrastructure. Public visibility is massive.",
    projectCardIcon: "project_card_neon_city_grid",
    clientPortrait: "portrait_mayor_vance",
    trophyIcon: "trophy_city_grid",
    locationBackdrop: "backdrop_neon_city_municipal",
    unlock: { phaseMin: 2, minRepTier: 4 },
    deposit: { formulaKey: "early" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Survey & Pilot Block",
        orderSpec: { targetTierRange: [4, 5], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.2, researchBonusFlat: 6 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop Intersection",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.1 },
      },
      {
        stageIndex: 2,
        stageTitle: "Eco Compliance Audit",
        orderSpec: { targetTierRange: [6, 7], requiresOpenOnly: true, ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.6, repBonusFlat: 18 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 3,
        stageTitle: "Grid Switch-over Ceremony",
        orderSpec: {
          targetTierRange: [8, 8],
          requiresCompatibility: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.4 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
    ],
    completionRewards: { cashMultiplier: 1.6, reputationMultiplier: 1.4, researchMultiplier: 1.4 },
    permanentPerk: "Municipal Trust",
    trophyId: "trophy_city_grid",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_festival_main_stage",
    title: "Festival of Sparks: Main Stage",
    locationName: "Riverfront Festival Grounds",
    client: { name: "Aria Kale", role: "Festival Director", tone: "visionary" },
    synopsis:
      "A spectacle contract with high stakes and zero tolerance for failure.",
    projectCardIcon: "project_card_festival_main_stage",
    clientPortrait: "portrait_aria_kale",
    trophyIcon: "trophy_backstage_pass",
    locationBackdrop: "backdrop_riverfront_festival",
    unlock: { phaseMin: 2, minRepTier: 5 },
    deposit: { formulaKey: "early" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Prototype Sequence",
        orderSpec: { targetTierRange: [5, 5], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.3 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Power & Safety Check",
        orderSpec: { targetTierRange: [6, 6], requiresOpenOnly: true, ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.5, repBonusFlat: 18 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 2,
        stageTitle: "Showtime Rig",
        orderSpec: { targetTierRange: [8, 9], requiresCompatibility: true, rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.6 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
    ],
    completionRewards: { cashMultiplier: 1.6, reputationMultiplier: 1.4, researchMultiplier: 1.4 },
    permanentPerk: "Showtime Reputation",
    trophyId: "trophy_backstage_pass",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_harbor_beacon",
    title: "Harbor Beacon Modernization",
    locationName: "Old Harbor Lighthouse District",
    client: { name: "Chief Rourke", role: "Port Authority", tone: "skeptical" },
    synopsis:
      "Reliability contract where weather, corrosion, and public safety matter more than flash.",
    projectCardIcon: "project_card_harbor_beacon",
    clientPortrait: "portrait_chief_rourke",
    trophyIcon: "trophy_harbor_lantern",
    locationBackdrop: "backdrop_old_harbor",
    unlock: { phaseMin: 2, minRepTier: 5 },
    deposit: { formulaKey: "early" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Saltproof Retrofit",
        orderSpec: { targetTierRange: [5, 6], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.2 },
        failPenalty: { type: "pressure", pressureIncrease: 5 },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop with Navigation Systems",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.1 },
      },
      {
        stageIndex: 2,
        stageTitle: "Storm Drill",
        orderSpec: { targetTierRange: [7, 7], requiresOpenOnly: true, rush: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 1.8 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 3,
        stageTitle: "Beacon Commissioning",
        orderSpec: { targetTierRange: [8, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.2 },
        failPenalty: { type: "pressure", pressureIncrease: 7 },
      },
    ],
    completionRewards: { cashMultiplier: 1.6, reputationMultiplier: 1.4, researchMultiplier: 1.4 },
    permanentPerk: "Reliability Stamp",
    trophyId: "trophy_harbor_lantern",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_metro_wayfinding",
    title: "Metro Wayfinding Overhaul",
    locationName: "Underground Metro Line",
    client: { name: "Commissioner Han", role: "Transit Commissioner", tone: "demanding" },
    synopsis:
      "Systemwide footprint and repetitive installs that test scalable operations.",
    projectCardIcon: "project_card_metro_wayfinding",
    clientPortrait: "portrait_commissioner_han",
    trophyIcon: "trophy_metro_badge",
    locationBackdrop: "backdrop_underground_metro",
    unlock: { phaseMin: 2, minRepTier: 6 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Platform Pilot",
        orderSpec: { targetTierRange: [5, 6], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.2 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Accessibility Compliance",
        orderSpec: { targetTierRange: [6, 6], ecoAudit: true, requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4, repBonusFlat: 20 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 2,
        stageTitle: "Interop Signaling",
        orderSpec: { targetTierRange: [7, 7], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.6 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
      {
        stageIndex: 3,
        stageTitle: "Night Service Rush",
        orderSpec: { targetTierRange: [7, 8], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 1.9 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 4,
        stageTitle: "Systemwide Launch",
        orderSpec: {
          targetTierRange: [9, 9],
          requiresCompatibility: true,
          rush: true,
        },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.7 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
    ],
    completionRewards: { cashMultiplier: 1.9, reputationMultiplier: 1.6, researchMultiplier: 1.5 },
    permanentPerk: "Transit Contract Pipeline",
    trophyId: "trophy_metro_badge",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_skyline_tower_facade",
    title: "Skyline Tower Signature Facade",
    locationName: "Glassspire Financial Tower",
    client: { name: "Liaison Sato", role: "Executive Liaison", tone: "demanding" },
    synopsis:
      "Prestige client with zero tolerance for public failure and huge visibility upside.",
    projectCardIcon: "project_card_skyline_tower",
    clientPortrait: "portrait_liaison_sato",
    trophyIcon: "trophy_glassspire_plaque",
    locationBackdrop: "backdrop_glassspire_tower",
    unlock: { phaseMin: 2, minRepTier: 6 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Design Mock-Up",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Energy Efficiency Certification",
        orderSpec: { targetTierRange: [6, 7], requiresOpenOnly: true, ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.6, researchBonusFlat: 12 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 2,
        stageTitle: "Facade Rollout",
        orderSpec: { targetTierRange: [8, 8], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 3,
        stageTitle: "Penthouse Showcase",
        orderSpec: { targetTierRange: [9, 9], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.6 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
    ],
    completionRewards: { cashMultiplier: 1.9, reputationMultiplier: 1.6, researchMultiplier: 1.5 },
    permanentPerk: "Prestige Clientele",
    trophyId: "trophy_glassspire_plaque",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_childrens_hospital",
    title: "Children's Hospital Nightlight Wing",
    locationName: "St. Luma Children's Hospital",
    client: { name: "Dr. Imani Reyes", role: "Chief Physician", tone: "warm" },
    synopsis:
      "Safety-first install with high scrutiny and high community stakes.",
    projectCardIcon: "project_card_childrens_hospital",
    clientPortrait: "portrait_dr_reyes",
    trophyIcon: "trophy_nightlight_ribbon",
    locationBackdrop: "backdrop_st_luma_hospital",
    unlock: { phaseMin: 2, minRepTier: 7 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Safety First Retrofit",
        orderSpec: { targetTierRange: [6, 7], requiresOpenOnly: true, ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.5, repBonusFlat: 24 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop Monitoring",
        orderSpec: { targetTierRange: [7, 7], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.7 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
      {
        stageIndex: 2,
        stageTitle: "Wing Opening",
        orderSpec: { targetTierRange: [9, 9], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 2.5, repBonusFlat: 40 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
    ],
    completionRewards: { cashMultiplier: 1.9, reputationMultiplier: 1.6, researchMultiplier: 1.5 },
    permanentPerk: "Community Trust",
    trophyId: "trophy_nightlight_ribbon",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_museum_exhibit",
    title: "Museum of Light: Retrospective Exhibit",
    locationName: "Museum of Light",
    client: { name: "Curator Elowen Shaw", role: "Curator", tone: "visionary" },
    synopsis:
      "A creative contract that leans into compatibility sets and signature builds.",
    projectCardIcon: "project_card_museum_exhibit",
    clientPortrait: "portrait_curator_shaw",
    trophyIcon: "trophy_curator_seal",
    locationBackdrop: "backdrop_museum_of_light",
    unlock: { phaseMin: 2, minRepTier: 7 },
    deposit: { formulaKey: "mid" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Gallery Concept Install",
        orderSpec: { targetTierRange: [6, 6], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.4 },
        failPenalty: { type: "pressure", pressureIncrease: 6 },
      },
      {
        stageIndex: 1,
        stageTitle: "Restoration Room Efficiency",
        orderSpec: { targetTierRange: [6, 7], requiresOpenOnly: true, ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.6 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 2,
        stageTitle: "Interactive Corridor",
        orderSpec: { targetTierRange: [7, 7], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.7 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.15 },
      },
      {
        stageIndex: 3,
        stageTitle: "Press Night Rush",
        orderSpec: { targetTierRange: [8, 8], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 4,
        stageTitle: "Featured Piece: Freedom in Light",
        orderSpec: { targetTierRange: [9, 10], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.8 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
    ],
    completionRewards: { cashMultiplier: 1.9, reputationMultiplier: 1.6, researchMultiplier: 1.5 },
    permanentPerk: "Exhibit Prestige",
    trophyId: "trophy_curator_seal",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_stadium_halftime",
    title: "Stadium Halftime Spectacle",
    locationName: "Titan Field Stadium",
    client: { name: "Jax Moreno", role: "Head of Events", tone: "demanding" },
    synopsis:
      "A pressure contract packed with rush installs and a high payout ceiling.",
    projectCardIcon: "project_card_stadium_halftime",
    clientPortrait: "portrait_jax_moreno",
    trophyIcon: "trophy_halftime",
    locationBackdrop: "backdrop_titan_field",
    unlock: { phaseMin: 2, minRepTier: 8 },
    deposit: { formulaKey: "late" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Rig Test",
        orderSpec: { targetTierRange: [7, 7], rush: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 1.7 },
        failPenalty: { type: "pressure", pressureIncrease: 7 },
      },
      {
        stageIndex: 1,
        stageTitle: "Interop Broadcast Sync",
        orderSpec: { targetTierRange: [8, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
      {
        stageIndex: 2,
        stageTitle: "Halftime Main System",
        orderSpec: { targetTierRange: [10, 10], requiresCompatibility: true, rush: true },
        deadline: { type: "installs", installsRemaining: 5 },
        stageRewards: { rewardMultiplier: 3.0 },
        failPenalty: { type: "pressure", pressureIncrease: 10 },
      },
    ],
    completionRewards: { cashMultiplier: 2.3, reputationMultiplier: 1.8, researchMultiplier: 1.6 },
    permanentPerk: "Stadium Grade",
    trophyId: "trophy_halftime",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_airport_runway",
    title: "Airport Runway Guidance Upgrade",
    locationName: "Neon City International Airport",
    client: { name: "Inspector Wren", role: "Safety Inspector", tone: "skeptical" },
    synopsis:
      "High scrutiny and procedural checks with a legitimacy payoff.",
    projectCardIcon: "project_card_airport_runway",
    clientPortrait: "portrait_inspector_wren",
    trophyIcon: "trophy_clearance_badge",
    locationBackdrop: "backdrop_neon_airport",
    unlock: { phaseMin: 2, minRepTier: 8 },
    deposit: { formulaKey: "late" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Taxiway Prototype",
        orderSpec: { targetTierRange: [7, 7], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 1.6 },
        failPenalty: { type: "pressure", pressureIncrease: 7 },
      },
      {
        stageIndex: 1,
        stageTitle: "Compliance Audit",
        orderSpec: { targetTierRange: [7, 8], ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 1.8 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 2,
        stageTitle: "Interop Control Integration",
        orderSpec: { targetTierRange: [8, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 7 },
        stageRewards: { rewardMultiplier: 2.1 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
      {
        stageIndex: 3,
        stageTitle: "Runway Commission",
        orderSpec: { targetTierRange: [10, 10], ecoAudit: true, requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 3.0 },
        failPenalty: { type: "pressure", pressureIncrease: 10 },
      },
    ],
    completionRewards: { cashMultiplier: 2.3, reputationMultiplier: 1.8, researchMultiplier: 1.6 },
    permanentPerk: "Certified Contractor",
    trophyId: "trophy_clearance_badge",
    narrativeBeats: NARRATIVE_GENERIC,
  },
  {
    id: "proj_international_expo",
    title: "International Light Expo Pavilion",
    locationName: "World Light Expo Grounds",
    client: { name: "Chair Solenne", role: "Expo Chair", tone: "visionary" },
    synopsis:
      "The capstone contract that crowns you as the industry standard-setter.",
    projectCardIcon: "project_card_international_expo",
    clientPortrait: "portrait_expo_chair_solenne",
    trophyIcon: "trophy_expo_laurel",
    locationBackdrop: "backdrop_world_expo",
    unlock: { phaseMin: 2, minRepTier: 9, minProjectsCompleted: 6 },
    deposit: { formulaKey: "capstone" },
    stages: [
      {
        stageIndex: 0,
        stageTitle: "Prototype Showcase",
        orderSpec: { targetTierRange: [7, 8], requiresCompatibility: true },
        deadline: { type: "installs", installsRemaining: 10 },
        stageRewards: { rewardMultiplier: 1.8 },
        failPenalty: { type: "pressure", pressureIncrease: 8 },
      },
      {
        stageIndex: 1,
        stageTitle: "Open Standard Demonstration",
        orderSpec: { targetTierRange: [8, 8], requiresOpenOnly: true },
        deadline: { type: "installs", installsRemaining: 9 },
        stageRewards: { rewardMultiplier: 2.0 },
        failPenalty: { type: "rep_debuff", repMultiplier: 0.9, remainingOrders: 3 },
      },
      {
        stageIndex: 2,
        stageTitle: "Sustainability Certification",
        orderSpec: { targetTierRange: [8, 9], requiresOpenOnly: true, ecoAudit: true },
        deadline: { type: "installs", installsRemaining: 8 },
        stageRewards: { rewardMultiplier: 2.2 },
        failPenalty: { type: "lose_deposit", loseDepositPercent: 0.2 },
      },
      {
        stageIndex: 3,
        stageTitle: "Press Deadline Rush",
        orderSpec: { targetTierRange: [9, 9], rush: true },
        deadline: { type: "installs", installsRemaining: 6 },
        stageRewards: { rewardMultiplier: 2.6 },
        failPenalty: { type: "pressure", pressureIncrease: 10 },
      },
      {
        stageIndex: 4,
        stageTitle: "Main Pavilion System",
        orderSpec: { targetTierRange: [10, 10], requiresCompatibility: true, rush: true },
        deadline: { type: "installs", installsRemaining: 5 },
        stageRewards: { rewardMultiplier: 3.5 },
        failPenalty: { type: "pressure", pressureIncrease: 12 },
      },
    ],
    completionRewards: { cashMultiplier: 3.0, reputationMultiplier: 2.2, researchMultiplier: 1.8 },
    permanentPerk: "Industry Standard-Setter",
    trophyId: "trophy_expo_laurel",
    narrativeBeats: NARRATIVE_GENERIC,
  },
];

export const PROJECT_DEFINITION_BY_ID = new Map(
  PROJECT_DEFINITIONS.map((project) => [project.id, project]),
);
