export type StorySpeaker =
  | "mentor"
  | "baron"
  | "customer"
  | "system"
  | "rd"
  | "tina";

export interface StoryBeat {
  id: string;
  speaker: StorySpeaker;
  line1: string;
  line2?: string;
  onceOnly?: boolean;
  portrait?: "portrait" | "confident" | "focused" | "delighted" | "concerned";
  priority?: "high" | "normal";
  momentLockMs?: number;
  category?:
    | "baron_fax"
    | "glowmail"
    | "mentor_tip"
    | "rd_memo"
    | "system"
    | "tutorial"
    | "inner_monologue"
    | "discovery"
    | "mission";
}

export const STORY_BEATS: Record<string, StoryBeat> = {
  tina_intro: {
    id: "tina_intro",
    speaker: "tina",
    line1: "Small shop, big city. Crownlight owns the standards.",
    line2: "First customer’s waiting. To win, I go Open and break free.",
    onceOnly: true,
    portrait: "delighted",
    category: "inner_monologue",
    priority: "high",
  },
  neighborhood_starter: {
    id: "neighborhood_starter",
    speaker: "system",
    line1: "Neighborhood unlocked: Starter Street.",
    onceOnly: true,
    category: "system",
  },
  neighborhood_hoa: {
    id: "neighborhood_hoa",
    speaker: "customer",
    line1: "Welcome to HOA Heights. Uniformity is the law here.",
    onceOnly: true,
  },
  neighborhood_downtown: {
    id: "neighborhood_downtown",
    speaker: "customer",
    line1: "Downtown wants game‑day colors in 30 seconds.",
    onceOnly: true,
  },
  neighborhood_certified: {
    id: "neighborhood_certified",
    speaker: "baron",
    line1: "Certified Install Week begins now.",
    onceOnly: true,
  },
  neighborhood_lockout: {
    id: "neighborhood_lockout",
    speaker: "system",
    line1: "Lockout Lane unlocked. Firmware Fridays ahead.",
    onceOnly: true,
    category: "system",
  },
  neighborhood_liberation: {
    id: "neighborhood_liberation",
    speaker: "mentor",
    line1: "Open Spark Workshop is ready when you are.",
    onceOnly: true,
  },
  tina_open_locked: {
    id: "tina_open_locked",
    speaker: "tina",
    line1: "Open Workshop isn’t online yet.",
    line2: "R&D + materials. Salvage will help.",
    onceOnly: true,
    portrait: "focused",
    category: "inner_monologue",
  },
  tina_upgrade_material: {
    id: "tina_upgrade_material",
    speaker: "tina",
    line1: "Upgrade material — got it.",
    line2: "This unlocks the Open Workshop.",
    onceOnly: true,
    portrait: "confident",
    category: "inner_monologue",
  },
  tina_compat_component: {
    id: "tina_compat_component",
    speaker: "tina",
    line1: "Compatibility components.",
    line2: "Save these for compatibility jobs.",
    onceOnly: true,
    portrait: "focused",
    category: "inner_monologue",
  },
  tina_momentum_tip: {
    id: "tina_momentum_tip",
    speaker: "tina",
    line1: "Nice merge streak.",
    line2: "I can trade it for a refill or cooldown cut.",
    onceOnly: true,
    portrait: "delighted",
    category: "inner_monologue",
  },
  tina_compat_order: {
    id: "tina_compat_order",
    speaker: "tina",
    line1:
      "Compatibility jobs need compatible parts. I should save those components.",
    onceOnly: true,
    portrait: "focused",
    category: "inner_monologue",
  },
  tina_phase2: {
    id: "tina_phase2",
    speaker: "tina",
    line1: "Freedom’s real. Now it’s about scale and clean installs.",
    onceOnly: true,
    portrait: "delighted",
    category: "inner_monologue",
  },
  council_unlock: {
    id: "council_unlock",
    speaker: "mentor",
    line1: "You didn't just win contracts - you changed minds.",
    line2: "The Standards Council is listening now.",
    onceOnly: true,
    portrait: "confident",
    category: "mentor_tip",
    priority: "high",
  },
  council_hearing: {
    id: "council_hearing",
    speaker: "system",
    line1: "Council hearing triggered.",
    line2: "Clear the objectives or lobby back to resolve it.",
    onceOnly: false,
    category: "system",
  },
  council_campaign_complete: {
    id: "council_campaign_complete",
    speaker: "tina",
    line1: "Standard ratified.",
    line2: "That's another rule written the open way.",
    onceOnly: false,
    portrait: "confident",
    category: "inner_monologue",
  },
  legacy_unlocked: {
    id: "legacy_unlocked",
    speaker: "mentor",
    line1: "Legacy Standards are now on the table.",
    line2:
      "You can begin a new cycle with doctrines and a custom starting kit.",
    onceOnly: true,
    portrait: "confident",
    category: "mentor_tip",
    priority: "high",
  },
  legacy_cycle_complete: {
    id: "legacy_cycle_complete",
    speaker: "tina",
    line1: "Cycle complete.",
    line2: "Run it again, tighter and stronger.",
    onceOnly: false,
    portrait: "delighted",
    category: "inner_monologue",
    priority: "high",
  },
  legacy_cycle_start: {
    id: "legacy_cycle_start",
    speaker: "system",
    line1: "Legacy cycle initialized.",
    line2: "Run progress reset. Doctrine loadout online.",
    onceOnly: false,
    category: "system",
  },
  tina_marketing: {
    id: "tina_marketing",
    speaker: "tina",
    line1: "Boosting order tiers for the next few jobs.",
    onceOnly: true,
    portrait: "confident",
    category: "inner_monologue",
  },
  mentor_waste_tip: {
    id: "mentor_waste_tip",
    speaker: "mentor",
    line1: "Those Baron shipments leave packaging waste.",
    line2: "Merge or recycle it for value.",
    onceOnly: true,
    portrait: "focused",
    category: "mentor_tip",
  },
  mentor_recycle_waste: {
    id: "mentor_recycle_waste",
    speaker: "mentor",
    line1: "Recycling waste can reduce workshop cooldowns.",
    onceOnly: true,
    portrait: "focused",
    category: "mentor_tip",
  },
  overdraw_baron: {
    id: "overdraw_baron",
    speaker: "baron",
    line1: "Borrow if you must. Cash up front.",
    line2: "And mind the mess.",
    onceOnly: true,
    category: "baron_fax",
  },
  overdraw_open: {
    id: "overdraw_open",
    speaker: "mentor",
    line1: "Open overdraw burns research.",
    line2: "Spend it with intent.",
    onceOnly: true,
    portrait: "focused",
    category: "mentor_tip",
  },
  overdraw_salvage: {
    id: "overdraw_salvage",
    speaker: "mentor",
    line1: "Overdrawing salvage eats waste.",
    line2: "No scrap? It'll cost cash.",
    onceOnly: true,
    portrait: "focused",
    category: "mentor_tip",
  },
  mentor_freedom_controller: {
    id: "mentor_freedom_controller",
    speaker: "mentor",
    line1: "Use it to convert locked kits into compatible open installs.",
    onceOnly: true,
    portrait: "confident",
    category: "mentor_tip",
  },
  mentor_scout_locked: {
    id: "mentor_scout_locked",
    speaker: "mentor",
    line1: "Locked scout is fast, but it raises pressure.",
    line2: "Use it for bursts, not habit.",
    onceOnly: true,
    portrait: "focused",
    category: "mentor_tip",
  },
  mentor_scout_tier: {
    id: "mentor_scout_tier",
    speaker: "mentor",
    line1: "Tier route improves drops but doesn’t change locked/open.",
    onceOnly: true,
    portrait: "focused",
    category: "mentor_tip",
  },
  mentor_warranty_stamp: {
    id: "mentor_warranty_stamp",
    speaker: "mentor",
    line1: "Stamp mode changes how penalties apply.",
    onceOnly: true,
    portrait: "concerned",
    category: "mentor_tip",
  },
  mentor_phase2_pressure: {
    id: "mentor_phase2_pressure",
    speaker: "mentor",
    line1:
      "Freedom’s real, but he can still squeeze margins. Clean installs protect rewards.",
    onceOnly: true,
    portrait: "concerned",
    category: "mentor_tip",
  },
  mentor_empire_contracts: {
    id: "mentor_empire_contracts",
    speaker: "mentor",
    line1: "You’re not surviving anymore. You’re delivering landmarks.",
    line2:
      "Empire Contracts turn every install into a public signal—finish them and the city follows.",
    onceOnly: true,
    portrait: "confident",
    category: "mentor_tip",
    priority: "high",
  },
  mentor_council_path: {
    id: "mentor_council_path",
    speaker: "mentor",
    line1:
      "Standards Council is next. Finish the capstone or stack six contracts.",
    line2: "Keep your reputation tier climbing to open the door.",
    onceOnly: true,
    portrait: "confident",
    category: "mentor_tip",
    priority: "high",
  },
  project_offer_generic: {
    id: "project_offer_generic",
    speaker: "mentor",
    line1: "Empire contract offers are live. Big deposits, bigger leverage.",
    onceOnly: true,
    portrait: "focused",
    category: "mentor_tip",
  },
  project_accept_generic: {
    id: "project_accept_generic",
    speaker: "tina",
    line1:
      "Deposit’s down. We build this in stages and make the skyline remember.",
    onceOnly: false,
    portrait: "confident",
    category: "inner_monologue",
  },
  project_stage_complete_generic: {
    id: "project_stage_complete_generic",
    speaker: "mentor",
    line1:
      "Stage delivered. Keep the rhythm—final payout is where the real weight lands.",
    onceOnly: false,
    portrait: "focused",
    category: "mentor_tip",
  },
  project_fail_generic: {
    id: "project_fail_generic",
    speaker: "mentor",
    line1: "Contract pulled. We take the hit and rebuild the pipeline.",
    onceOnly: false,
    portrait: "concerned",
    category: "mentor_tip",
  },
  project_complete_generic: {
    id: "project_complete_generic",
    speaker: "tina",
    line1: "Landmark delivered. We’re not just free—we’re the standard now.",
    onceOnly: false,
    portrait: "delighted",
    category: "inner_monologue",
  },
  baron_contract_live: {
    id: "baron_contract_live",
    speaker: "baron",
    line1: "Contract live. You’ll deliver locked kits for cash.",
    onceOnly: true,
    portrait: "confident",
    category: "baron_fax",
  },
  baron_open_unlocked: {
    id: "baron_open_unlocked",
    speaker: "baron",
    line1: "So you found an open workshop.",
    line2: "Let’s see how long it lasts.",
    onceOnly: true,
    portrait: "confident",
    category: "baron_fax",
    priority: "high",
  },
  dependency_20: {
    id: "dependency_20",
    speaker: "baron",
    line1: "Audit notice: compliance review imminent.",
    line2: "Last chance to kneel. — Bulb Baron",
    onceOnly: true,
    priority: "high",
  },
  dependency_40: {
    id: "dependency_40",
    speaker: "customer",
    line1: "Open installs are holding steady.",
    line2: "People are starting to talk.",
    onceOnly: true,
    priority: "high",
  },
  dependency_60: {
    id: "dependency_60",
    speaker: "baron",
    line1: "You’re experimenting. I see it.",
    line2: "Compliance is safety.",
    onceOnly: true,
    priority: "high",
  },
  dependency_80: {
    id: "dependency_80",
    speaker: "mentor",
    line1: "First open supply came through.",
    line2: "Tiny crack in the wall.",
    onceOnly: true,
    priority: "high",
  },
  dependency_100: {
    id: "dependency_100",
    speaker: "baron",
    line1: "Certified supply active.",
    line2: "Compliance expected.",
    onceOnly: true,
    priority: "high",
  },
  baron_attention: {
    id: "baron_attention",
    speaker: "baron",
    line1: "My attention doesn't drift, Tina.",
    line2: "Audits tighten when you push too hard.",
    onceOnly: true,
    priority: "high",
    category: "baron_fax",
  },
  rd_unlock: {
    id: "rd_unlock",
    speaker: "mentor",
    line1: "We stop begging when we can build.",
    onceOnly: true,
    priority: "high",
  },
  rd_blueprint: {
    id: "rd_blueprint",
    speaker: "rd",
    line1: "He locked the controller. So… we unlock the lock.",
    onceOnly: true,
    priority: "high",
  },
  freedom_first_use: {
    id: "freedom_first_use",
    speaker: "tina",
    line1: "That sound? Freedom.",
    line2: "Okay, that’s gorgeous.",
    onceOnly: true,
    portrait: "delighted",
    priority: "high",
  },
  baron_offer: {
    id: "baron_offer",
    speaker: "baron",
    line1: "A signature is just a hug… in legal form.",
    onceOnly: true,
    priority: "high",
  },
  baron_offer_prompt: {
    id: "baron_offer_prompt",
    speaker: "mentor",
    line1: "He’s offering speed. Read the fine print.",
    line2: "If you want to win Phase 1, go Open. This pulls the other way.",
    onceOnly: true,
    category: "tutorial",
    priority: "high",
  },
  baron_offer_return: {
    id: "baron_offer_return",
    speaker: "baron",
    line1: "Still glowing? Let’s talk certification.",
    line2: "Protected territory included.",
    onceOnly: true,
    category: "baron_fax",
  },
  tutorial_merge_1: {
    id: "tutorial_merge_1",
    speaker: "mentor",
    line1: "Parts are your inventory.",
    line2: "Tracks are your first install part.",
    onceOnly: true,
    category: "tutorial",
    priority: "high",
    momentLockMs: 600,
  },
  tutorial_merge_2: {
    id: "tutorial_merge_2",
    speaker: "tina",
    line1: "Segment built.",
    line2: "Higher tiers unlock better orders.",
    onceOnly: true,
    portrait: "confident",
    category: "tutorial",
    priority: "high",
    momentLockMs: 600,
  },
  tutorial_order: {
    id: "tutorial_order",
    speaker: "customer",
    line1: "Please—no flicker. My neighbors judge.",
    onceOnly: true,
    category: "tutorial",
    priority: "high",
  },
  tina_customer_reply: {
    id: "tina_customer_reply",
    speaker: "tina",
    line1: "You got it. No flicker, just glow.",
    line2: "Cash keeps us open. Reputation opens neighborhoods.",
    onceOnly: true,
    portrait: "delighted",
    priority: "high",
  },
  tutorial_upgrade: {
    id: "tutorial_upgrade",
    speaker: "tina",
    line1: "Space is oxygen.",
    line2: "You can’t build an empire in a closet.",
    onceOnly: true,
    portrait: "confident",
    category: "tutorial",
    priority: "high",
  },
  backpack_unlocked: {
    id: "backpack_unlocked",
    speaker: "mentor",
    line1: "Backpack unlocked. Store extras to keep the board clear.",
    onceOnly: true,
    category: "mentor_tip",
    priority: "high",
  },
  first_session_certified: {
    id: "first_session_certified",
    speaker: "baron",
    line1: "Certified clients pay full for locked kits.",
    line2: "Open installs take a deduction.",
    onceOnly: true,
    category: "baron_fax",
    priority: "high",
  },
  tutorial_baron_choice: {
    id: "tutorial_baron_choice",
    speaker: "baron",
    line1: "Choice is a luxury. Enjoy it.",
    onceOnly: true,
    category: "tutorial",
    priority: "high",
  },
  tutorial_locked_merge: {
    id: "tutorial_locked_merge",
    speaker: "mentor",
    line1: "Locked parts stay locked when merged.",
    line2: "Power now, dependency later.",
    onceOnly: true,
    category: "tutorial",
    priority: "high",
    momentLockMs: 600,
  },
  tutorial_ready: {
    id: "tutorial_ready",
    speaker: "mentor",
    line1: "Two more installs and you’re on your own.",
    line2: "To win Phase 1, go Open and drive Dependency down.",
    onceOnly: true,
    category: "tutorial",
    priority: "high",
  },
  baron_offer_accept: {
    id: "baron_offer_accept",
    speaker: "baron",
    line1: "Welcome to Crownlight Certified.",
    line2: "Exclusive glow, protected zip codes.",
    onceOnly: true,
    category: "baron_fax",
    priority: "high",
  },
  baron_offer_decline: {
    id: "baron_offer_decline",
    speaker: "mentor",
    line1: "Slow and steady. Open keeps you flexible.",
    onceOnly: true,
    category: "mentor_tip",
    priority: "high",
  },
  tina_baron_accept: {
    id: "tina_baron_accept",
    speaker: "tina",
    line1: "Alright, Baron. I’ll take the boost.",
    line2: "But I’m reading the fine print.",
    onceOnly: true,
    portrait: "confident",
    category: "inner_monologue",
    priority: "high",
  },
  tina_baron_decline: {
    id: "tina_baron_decline",
    speaker: "tina",
    line1: "Not today, Baron.",
    line2: "I’m building this my way.",
    onceOnly: true,
    portrait: "confident",
    category: "inner_monologue",
    priority: "high",
  },
  discover_track: {
    id: "discover_track",
    speaker: "mentor",
    line1: "Track (Tier 2) — used in basic installs.",
    line2: "Merge Tracks to build a Segment.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_segment: {
    id: "discover_segment",
    speaker: "mentor",
    line1: "Segment (Tier 3) unlocked.",
    line2: "Higher tiers unlock better orders.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_smartkit: {
    id: "discover_smartkit",
    speaker: "mentor",
    line1: "Smart Kit (Tier 4) — premium installs begin here.",
    line2: "Hold space. These pay well.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_system: {
    id: "discover_system",
    speaker: "mentor",
    line1: "System (Tier 5) — signature installs only.",
    line2: "Expect a premium showcase order.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_array: {
    id: "discover_array",
    speaker: "mentor",
    line1: "Routing Array (Tier 6) unlocked.",
    line2: "You’re mapping real runs now.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_spine: {
    id: "discover_spine",
    speaker: "mentor",
    line1: "Network Spine (Tier 7) — major build scale.",
    line2: "The business is growing.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_stack: {
    id: "discover_stack",
    speaker: "mentor",
    line1: "Control Stack (Tier 8) unlocked.",
    line2: "Time to sync complex installs.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_grid: {
    id: "discover_grid",
    speaker: "mentor",
    line1: "Signature Grid (Tier 9) online.",
    line2: "This is artistry with infrastructure.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_kingdom: {
    id: "discover_kingdom",
    speaker: "mentor",
    line1: "Kingdom Install (Tier 10) achieved.",
    line2: "You’re ready for a showcase.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 800,
  },
  discover_lattice: {
    id: "discover_lattice",
    speaker: "mentor",
    line1: "Civic Lattice (Tier 11) online.",
    line2: "Phase 2 just got real.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 800,
  },
  discover_matrix: {
    id: "discover_matrix",
    speaker: "mentor",
    line1: "Beacon Matrix (Tier 12) unlocked.",
    line2: "Your installs are city-visible now.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 800,
  },
  discover_nexus: {
    id: "discover_nexus",
    speaker: "mentor",
    line1: "Metro Nexus (Tier 13) achieved.",
    line2: "Queue up the Phase 2 showcase.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 900,
  },
  discover_core: {
    id: "discover_core",
    speaker: "mentor",
    line1: "Skyline Core (Tier 14) unlocked.",
    line2: "Phase 3 installs are now in play.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 900,
  },
  discover_atlas: {
    id: "discover_atlas",
    speaker: "mentor",
    line1: "Atlas Network (Tier 15) online.",
    line2: "You’re shaping entire districts at once.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 900,
  },
  discover_legacy_standard: {
    id: "discover_legacy_standard",
    speaker: "mentor",
    line1: "Legacy Standard (Tier 16) achieved.",
    line2: "This is the benchmark now.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 1000,
  },
  tier10_showcase: {
    id: "tier10_showcase",
    speaker: "mentor",
    line1: "Signature install completed. The district takes notice.",
    line2: "Momentum like this reshapes your whole operation.",
    onceOnly: true,
    category: "mission",
    priority: "high",
    momentLockMs: 900,
  },
  tier13_showcase: {
    id: "tier13_showcase",
    speaker: "mentor",
    line1: "Metro showcase delivered.",
    line2: "Your operation is now Phase 3-capable.",
    onceOnly: true,
    category: "mission",
    priority: "high",
    momentLockMs: 950,
  },
  tier16_showcase: {
    id: "tier16_showcase",
    speaker: "mentor",
    line1: "Legacy showcase complete.",
    line2: "You’ve set the citywide standard.",
    onceOnly: true,
    category: "mission",
    priority: "high",
    momentLockMs: 1000,
  },
  discover_locked: {
    id: "discover_locked",
    speaker: "baron",
    line1: "Locked parts hit hotter… and tighten the leash.",
    line2: "Dependency starts maxed. Locked installs reinforce it.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_locked_merge: {
    id: "discover_locked_merge",
    speaker: "mentor",
    line1: "Locked + Open → Locked.",
    line2: "Once it locks, it spreads.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  discover_compatible: {
    id: "discover_compatible",
    speaker: "rd",
    line1: "Compatible kits unlock special compatibility installs.",
    line2: "Still open. Still flexible.",
    onceOnly: true,
    category: "discovery",
    priority: "high",
    momentLockMs: 600,
  },
  first_session_choice: {
    id: "first_session_choice",
    speaker: "mentor",
    line1: "Two paths: open reliability or certified profit.",
    line2: "Complete one to set your tone.",
    onceOnly: true,
    category: "mission",
    priority: "high",
  },
  mission_mentor_complete: {
    id: "mission_mentor_complete",
    speaker: "mentor",
    line1: "Good work. Short goals build real instincts.",
    line2: "Keep the shop steady.",
    onceOnly: true,
    category: "mission",
  },
  mission_baron_complete: {
    id: "mission_baron_complete",
    speaker: "baron",
    line1: "Efficient execution. Certified growth continues.",
    line2: "Expect further incentives.",
    onceOnly: true,
    category: "mission",
  },
  mission_rd_complete: {
    id: "mission_rd_complete",
    speaker: "rd",
    line1: "Data logged. Compatibility metrics improving.",
    line2: "Proceed to the next objective.",
    onceOnly: true,
    category: "mission",
  },
  mission_customer_complete: {
    id: "mission_customer_complete",
    speaker: "customer",
    line1: "That glow is perfect.",
    line2: "I’m telling the whole block.",
    onceOnly: true,
    category: "mission",
  },
  mission_system_complete: {
    id: "mission_system_complete",
    speaker: "system",
    line1: "Goal logged. Performance rating up.",
    line2: "Maintain momentum.",
    onceOnly: true,
    category: "mission",
  },
  lockout_begin: {
    id: "lockout_begin",
    speaker: "system",
    line1: "Audit active — dependency won’t drop below 20.",
    onceOnly: true,
    category: "system",
  },
  tina_lockout_react: {
    id: "tina_lockout_react",
    speaker: "tina",
    line1: "They noticed. Okay. We move.",
    line2: "Kneel… or build.",
    onceOnly: true,
    portrait: "concerned",
    category: "inner_monologue",
  },
  lockout_choice_baron: {
    id: "lockout_choice_baron",
    speaker: "baron",
    line1: "Emergency compliance crate authorized.",
    line2: "Sign and the audit passes.",
    onceOnly: true,
    category: "baron_fax",
  },
  lockout_choice_lab: {
    id: "lockout_choice_lab",
    speaker: "rd",
    line1: "Countermeasure requests incoming.",
    line2: "Build the controller.",
    onceOnly: true,
    category: "rd_memo",
  },
  lockout_resolve_baron: {
    id: "lockout_resolve_baron",
    speaker: "baron",
    line1: "Audit closed. Compliance noted.",
    line2: "Certified supply will continue.",
    onceOnly: true,
    category: "baron_fax",
  },
  lockout_resolve_freedom: {
    id: "lockout_resolve_freedom",
    speaker: "mentor",
    line1: "You slipped the audit. Breathe.",
    line2: "Now build on your terms.",
    onceOnly: true,
    category: "mentor_tip",
  },
  liberation_victory: {
    id: "liberation_victory",
    speaker: "mentor",
    line1: "You're free. This is your shop now.",
    line2: "Phase Two starts here.",
    onceOnly: true,
    priority: "high",
    category: "mentor_tip",
  },
  phase2_goal: {
    id: "phase2_goal",
    speaker: "mentor",
    line1: "Open Spark is live. Let's prove it.",
    line2: "First goal: deliver a compatible install.",
    onceOnly: true,
    priority: "high",
    category: "mentor_tip",
  },
  rd_memo_1: {
    id: "rd_memo_1",
    speaker: "rd",
    line1: "Prototype bench calibration complete.",
    category: "rd_memo",
  },
  rd_memo_2: {
    id: "rd_memo_2",
    speaker: "rd",
    line1: "Open-standard diagnostics are clean.",
    category: "rd_memo",
  },
  rd_memo_3: {
    id: "rd_memo_3",
    speaker: "rd",
    line1: "Controller blueprint fragments acquired.",
    category: "rd_memo",
  },
  rd_memo_4: {
    id: "rd_memo_4",
    speaker: "rd",
    line1: "Freedom Controller wants a clean signal.",
    category: "rd_memo",
  },
  mentor_tip_1: {
    id: "mentor_tip_1",
    speaker: "mentor",
    line1: "Merge first. Think later.",
    category: "mentor_tip",
  },
  mentor_tip_2: {
    id: "mentor_tip_2",
    speaker: "mentor",
    line1: "If it feels too good early, check the fine print.",
    category: "mentor_tip",
  },
  mentor_tip_3: {
    id: "mentor_tip_3",
    speaker: "mentor",
    line1: "Space is power. Keep a slot open.",
    category: "mentor_tip",
  },
  mentor_tip_4: {
    id: "mentor_tip_4",
    speaker: "mentor",
    line1: "Open kits earn research. Research earns freedom.",
    category: "mentor_tip",
  },
  mentor_tip_5: {
    id: "mentor_tip_5",
    speaker: "mentor",
    line1: "Locked sells fast. Open lasts long.",
    category: "mentor_tip",
  },
  mentor_tip_6: {
    id: "mentor_tip_6",
    speaker: "mentor",
    line1: "Never chase a quota at the cost of control.",
    category: "mentor_tip",
  },
  glowmail_1: {
    id: "glowmail_1",
    speaker: "customer",
    line1: "GlowMail: The patio looks wedding-ready.",
    category: "glowmail",
  },
  glowmail_2: {
    id: "glowmail_2",
    speaker: "customer",
    line1: "GlowMail: HOA approved your uniformity.",
    category: "glowmail",
  },
  glowmail_3: {
    id: "glowmail_3",
    speaker: "customer",
    line1: "GlowMail: Game day glow was a hit.",
    category: "glowmail",
  },
  glowmail_4: {
    id: "glowmail_4",
    speaker: "customer",
    line1: "GlowMail: Minimalist client loved the calm light.",
    category: "glowmail",
  },
  glowmail_5: {
    id: "glowmail_5",
    speaker: "customer",
    line1: "GlowMail: Tech dad wants exportable presets.",
    category: "glowmail",
  },
  glowmail_6: {
    id: "glowmail_6",
    speaker: "customer",
    line1: "GlowMail: Neighbor rivalry escalated. You won.",
    category: "glowmail",
  },
  glowmail_7: {
    id: "glowmail_7",
    speaker: "customer",
    line1: "GlowMail: Boutique traffic is up after your install.",
    category: "glowmail",
  },
  glowmail_8: {
    id: "glowmail_8",
    speaker: "customer",
    line1: "GlowMail: Thanks for keeping it local.",
    category: "glowmail",
  },
  baron_fax_1: {
    id: "baron_fax_1",
    speaker: "baron",
    line1: "BaronFax: Crownlight Certified shipments prioritized.",
    line2: "Compliance keeps your zip code protected.",
    category: "baron_fax",
  },
  baron_fax_2: {
    id: "baron_fax_2",
    speaker: "baron",
    line1: "BaronFax: Exclusive is a feeling. Compliance is a requirement.",
    category: "baron_fax",
  },
  baron_fax_3: {
    id: "baron_fax_3",
    speaker: "baron",
    line1:
      "BaronFax: Quota season begins Monday. Glow targets are non-negotiable.",
    category: "baron_fax",
  },
  baron_fax_4: {
    id: "baron_fax_4",
    speaker: "baron",
    line1: "BaronFax: Firmware Friday rolls out tonight.",
    line2: "Reboots ensure quality.",
    category: "baron_fax",
  },
  baron_fax_5: {
    id: "baron_fax_5",
    speaker: "baron",
    line1: "BaronFax: Your territory is protected (terms apply).",
    category: "baron_fax",
  },
  baron_fax_6: {
    id: "baron_fax_6",
    speaker: "baron",
    line1: "BaronFax: New patterns available in the Crownlight app.",
    line2: "Permissions updated for your convenience.",
    category: "baron_fax",
  },
  baron_fax_7: {
    id: "baron_fax_7",
    speaker: "baron",
    line1: "BaronFax: We noticed open kits in certified installs.",
    line2: "Please align with standards.",
    category: "baron_fax",
  },
  baron_fax_8: {
    id: "baron_fax_8",
    speaker: "baron",
    line1: "BaronFax: Supply chain optimized for loyal partners.",
    category: "baron_fax",
  },
  tina_thought_1: {
    id: "tina_thought_1",
    speaker: "tina",
    line1: "If it glows, it goes.",
    portrait: "portrait",
    category: "inner_monologue",
  },
  tina_thought_2: {
    id: "tina_thought_2",
    speaker: "tina",
    line1: "Slow and steady, Tina. No shortcuts you can’t undo.",
    portrait: "focused",
    category: "inner_monologue",
  },
  tina_thought_3: {
    id: "tina_thought_3",
    speaker: "tina",
    line1: "Customers want magic. I deliver science.",
    portrait: "portrait",
    category: "inner_monologue",
  },
  tina_thought_4: {
    id: "tina_thought_4",
    speaker: "tina",
    line1: "Locked kits sparkle. So do contracts.",
    portrait: "focused",
    category: "inner_monologue",
  },
  tina_thought_5: {
    id: "tina_thought_5",
    speaker: "tina",
    line1: "One more merge and this board breathes again.",
    portrait: "focused",
    category: "inner_monologue",
  },
  tina_thought_6: {
    id: "tina_thought_6",
    speaker: "tina",
    line1: "Open path’s slower, but it feels like mine.",
    portrait: "portrait",
    category: "inner_monologue",
  },
  lockout_lab_complete: {
    id: "lockout_lab_complete",
    speaker: "rd",
    line1: "Countermeasure Controller ready.",
    line2: "Slip the audit when you're ready.",
    onceOnly: true,
    category: "rd_memo",
  },
};

export const BARON_FAX_BEATS = [
  "baron_fax_1",
  "baron_fax_2",
  "baron_fax_3",
  "baron_fax_4",
  "baron_fax_5",
  "baron_fax_6",
  "baron_fax_7",
  "baron_fax_8",
];

export const GLOWMAIL_BEATS = [
  "glowmail_1",
  "glowmail_2",
  "glowmail_3",
  "glowmail_4",
  "glowmail_5",
  "glowmail_6",
  "glowmail_7",
  "glowmail_8",
];

export const MENTOR_TIP_BEATS = [
  "mentor_tip_1",
  "mentor_tip_2",
  "mentor_tip_3",
  "mentor_tip_4",
  "mentor_tip_5",
  "mentor_tip_6",
];

export const RD_MEMO_BEATS = [
  "rd_memo_1",
  "rd_memo_2",
  "rd_memo_3",
  "rd_memo_4",
];

export const TINA_BEATS = [
  "tina_thought_1",
  "tina_thought_2",
  "tina_thought_3",
  "tina_thought_4",
  "tina_thought_5",
  "tina_thought_6",
];

export const ORDER_FLAVOR_TEXTS = [
  "HOA says: “Warm white only.” HOA says a lot of things.",
  "Client wants subtle. Their neighbor wants “seen from space.”",
  "Birthday party. Kid requested “dragon mode.” Please don’t ask.",
  "Tech dad wants app control. He brought a spreadsheet.",
  "Cozy minimalist: “No wires visible.” Good luck.",
  "Sports superfan wants team colors in 30 seconds.",
  "Neighbor rivalry: “Brighter than the Joneses.”",
  "A shop owner wants a glow that says premium, not loud.",
  "A skeptic says: no subscriptions, no surprises.",
  "HOA president: no blinking. Ever.",
  "Customer asks for a calm glow, no visible wiring.",
  "Next-door rivalry request: brighter than last year.",
];
